# Generated by Django 4.0.4 on 2022-05-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='product_description',
            field=models.CharField(max_length=1500),
        ),
    ]
