# Generated by Django 2.2.10 on 2022-06-19 14:40

from django.db import migrations, models
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_product_list_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved_Product_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('expected_price', models.CharField(max_length=12)),
                ('product_description', models.CharField(max_length=1500)),
                ('product_image1', models.FileField(null=True, upload_to=seller.models.user_directory_path2, verbose_name='')),
                ('product_image2', models.FileField(null=True, upload_to=seller.models.user_directory_path2, verbose_name='')),
                ('product_image3', models.FileField(null=True, upload_to=seller.models.user_directory_path2, verbose_name='')),
                ('product_image4', models.FileField(null=True, upload_to=seller.models.user_directory_path2, verbose_name='')),
            ],
            options={
                'db_table': 'approved_product_table',
            },
        ),
        migrations.AlterField(
            model_name='product_list',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
