# Generated by Django 4.0.4 on 2022-05-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='G_Sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
