# Generated by Django 2.2.10 on 2022-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up_in', '0002_alter_g_sign_up_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g_sign_up',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
