# Generated by Django 4.0.5 on 2022-06-29 19:44

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('expected_price', models.CharField(max_length=12)),
                ('product_description', models.CharField(max_length=1500)),
                ('product_image1', models.FileField(null=True, upload_to=main.models.user_directory_path2, verbose_name='')),
                ('product_image2', models.FileField(null=True, upload_to=main.models.user_directory_path2, verbose_name='')),
                ('product_image3', models.FileField(null=True, upload_to=main.models.user_directory_path2, verbose_name='')),
                ('product_image4', models.FileField(null=True, upload_to=main.models.user_directory_path2, verbose_name='')),
                ('status', models.CharField(max_length=50, null=True)),
                ('remark', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
