# Generated by Django 4.0.5 on 2022-06-30 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstable',
            name='product_created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productstable',
            name='status_updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
